repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff (lint + import sort)
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: check-added-large-files
        name: Check for added large files
        entry: check-added-large-files
        language: system
      - id: check-toml
        name: Check Toml
        entry: check-toml
        language: system
        types: [toml]
      - id: check-yaml
        name: Check Yaml
        entry: check-yaml
        language: system
        types: [yaml]
      - id: end-of-file-fixer
        name: Fix End of Files
        entry: end-of-file-fixer
        language: system
        types: [text]
        stages: [pre-commit, pre-push, manual]
      - id: trailing-whitespace
        name: Trim Trailing Whitespace
        entry: trailing-whitespace-fixer
        language: system
        types: [text]
        stages: [pre-commit, pre-push, manual]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
